### ISSUE TITLE
Arithmetic exception (win32 or GCC related?)

### ISSUE THREAD

**Issue by timdevorg** [npxtune/chisel8#13]
# Description
Compiling the project on win32 using MinGW-w64 and GCC works, however, the `0xFX33` opcode causes an arithmetic exception which crashes the application (tested via Pong 1-player ROM). When commenting out the opcode, everything works as expected. This should not happen, even if this issue does not appear on my dev setup (macOS & clang).

The line(s) affected:
https://github.com/npxtune/chisel8/blob/f33b0607e79c46eaff477a499378816a8ca9bc38/src/core/emu_core.c#L259

# TODO

- [x] investigate the cause for the exception
- [x] find out if it's win32 or GCC specific
- [x] fix the bug

---

```
This needs to get fixed before v1.0 is meant to be released.
```

**Comment by timdevorg** [comment]
Seems like those lines of code were incorrect and would sometimes try to divide by 0, causing the arithmetic exception.
I revised the lines of code, this is much simpler and cleaner and does not do some convoluted things:

```C
                case (0x33):
                    N1 = chip8->reg[X];
                    chip8->ram[(chip8->I) % RAM_SIZE] = N1 / 100;
                    chip8->ram[(chip8->I + 1) % RAM_SIZE] = (N1 % 100) / 10;
                    chip8->ram[(chip8->I + 2) % RAM_SIZE] = N1 % 10;
                    break;
```

Will be merging this with the next PR.

**Comment by timdevorg** [comment]
fixed with #14
